package com.base.donnees;
// Generated 24 mars 2022 à 09:24:39 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Niveau generated by hbm2java
 */
@Entity
@Table(name = "niveau", catalog = "gestion_scolarite_javafx")
public class Niveau implements java.io.Serializable {

	private Integer idNiveau;
	private String libelle;
	private double montantScolarite;
	private Set<Etudiant> etudiants = new HashSet<Etudiant>(0);

	public Niveau() {
	}

	public Niveau(String libelle, double montantScolarite) {
		this.libelle = libelle;
		this.montantScolarite = montantScolarite;
	}

	public Niveau(String libelle, double montantScolarite, Set<Etudiant> etudiants) {
		this.libelle = libelle;
		this.montantScolarite = montantScolarite;
		this.etudiants = etudiants;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_niveau", unique = true, nullable = false)
	public Integer getIdNiveau() {
		return this.idNiveau;
	}

	public void setIdNiveau(Integer idNiveau) {
		this.idNiveau = idNiveau;
	}

	@Column(name = "libelle", nullable = false, length = 50)
	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	@Column(name = "montant_scolarite", nullable = false, precision = 22, scale = 0)
	public double getMontantScolarite() {
		return this.montantScolarite;
	}

	public void setMontantScolarite(double montantScolarite) {
		this.montantScolarite = montantScolarite;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "niveau")
	public Set<Etudiant> getEtudiants() {
		return this.etudiants;
	}

	public void setEtudiants(Set<Etudiant> etudiants) {
		this.etudiants = etudiants;
	}

}
