package application;

import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import javafx.scene.control.Label;
import javafx.scene.control.ToggleGroup;
import javafx.scene.layout.AnchorPane;
import javafx.scene.layout.BorderPane;
import javafx.stage.Stage;
import javafx.stage.StageStyle;
import net.bytebuddy.asm.Advice.Exit;


public class AccueilController  {
	@FXML
	private Button close;
	@FXML
	private Label AgentEnLigne;
	@FXML
	private Label matricule;
	@FXML
	private Button AjouetEtudiant;
	@FXML
	private Button ModifierEtudiant;
	@FXML
	private Button listeEtudiant;
	@FXML
	private Button supprimerEtudiant;
	@FXML
	private Button versement;
	@FXML
	private Button deconnexion;
	@FXML
	private Button ajouterAgent;
	@FXML
	private Button supprimerAgent;
	@FXML
	private AnchorPane contenu;
	@FXML
	private BorderPane ContenuPrincipal;
	@FXML
	private ToggleGroup genre;

	
	
	
	//Contenu.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
	public void chargementFonction(String s) {
		try {
					
					AnchorPane pane = FXMLLoader.load(getClass().getResource(s));
					pane.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
					contenu.getChildren().setAll(pane);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
	}
	//Mise a jour du label
	public void agentenligne (String nom, String prenom, String matriculee) {
		AgentEnLigne.setText(nom+" "+prenom);
		matricule.setText(matriculee);
	}
	
	//Recuperation de matricule
	public String getMatriculeAgentenligne() {
		String s = matricule.getText();
		return s;
	}
	
	// Event Listener on Button[#close].onAction
	@FXML
	public void closeOnAction(ActionEvent event) {
		// TODO Autogenerated
		
		((Node)event.getSource()).getScene().getWindow().hide();
	}
	// Event Listener on Button[#AjouetEtudiant].onAction
	@FXML
	public void AjouetEtudiantOnAction(ActionEvent event) throws IOException {
		// TODO Autogenerated
	
		FXMLLoader loader = new FXMLLoader(getClass().getResource("AjouterEtudiant.fxml"));
		AnchorPane pane=null;
			pane = (AnchorPane) loader.load();

		pane.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
		contenu.getChildren().setAll(pane);
		AjouterEtudiantController vv = loader.getController();
		vv.setidAgent(matricule.getText());
	}
	// Event Listener on Button[#ModifierEtudiant].onAction
	@FXML
	public void ModifierEtudiantOnAction(ActionEvent event) {
		// TODO Autogenerated
		chargementFonction("ModifierEtudiant.fxml");
	}
	// Event Listener on Button[#SupprimerEtudiant].onAction
		@FXML
		public void supprimerEtudiantOnAction(ActionEvent event) {
			// TODO Autogenerated
			chargementFonction("SupprimerEtudiant.fxml");
		}
	// Event Listener on Button[#listeEtudiant].onAction
	@FXML
	public void listeEtudiantOnAction(ActionEvent event) {
		// TODO Autogenerated
		chargementFonction("listeEtudiant.fxml");
	}
	// Event Listener on Button[#versement].onAction
	@FXML
	public void versementOnAction(ActionEvent event) {
		// TODO Autogenerated
		
		FXMLLoader loader = new FXMLLoader(getClass().getResource("Versement.fxml"));
		AnchorPane pane=null;
		try {
			pane = (AnchorPane) loader.load();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		pane.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
		contenu.getChildren().setAll(pane);
		VersementController vv = loader.getController();
		vv.Id_agentdefaut(matricule.getText());
	}
	// Event Listener on Button[#deconnexion].onAction
	@FXML
	public void deconnexionOnAction(ActionEvent event) {
		// TODO Autogenerated
		((Node)event.getSource()).getScene().getWindow().hide();
		//scene.stage.close();
		
		try {
			
			Parent root;
			Stage primaryStage = new Stage();
			primaryStage.initStyle(StageStyle.UNDECORATED);
			((Node)event.getSource()).getScene().getWindow().hide();
			root = FXMLLoader.load(Main.class.getResource("authentification.fxml"));
			Scene scene = new Scene(root);
			scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
			primaryStage.setScene(scene);
			primaryStage.show();
		} catch(Exception e) {
			e.printStackTrace();
		}
	}
	// Event Listener on Button[#ajouterAgent].onAction
	@FXML
	public void ajouterAgentOnAction(ActionEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader = new FXMLLoader(getClass().getResource("ajouterAgent.fxml"));
		AnchorPane pane = (AnchorPane) loader.load();
		pane.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
		contenu.getChildren().setAll(pane);
		
		ajouterAgentController controller = loader.getController();
		controller.getBymatricule(matricule.getText());
		//recuperrationDirecteur(pseudo.getText(), passe.getText());
		//chargementFonction("ajouterAgent.fxml");
	}
	// Event Listener on Button[#supprimerAgent].onAction
	@FXML
	public void supprimerAgentOnAction(ActionEvent event) {
		// TODO Autogenerated
		chargementFonction("supprimerAgent.fxml");
	}
}
