package application;

import com.base.donnees.Agentdescolarite;
import com.gestion.dao.AgentdescolariteDao;
import com.gestion.dao.DirecteurDao;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;

import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import javafx.scene.control.Alert.AlertType;


public class ajouterAgentController {
	@FXML
	private TextField nom;
	@FXML
	private TextField prenom;
	@FXML
	private TextField mail;
	@FXML
	private TextField pseudo;
	@FXML
	private TextField motPasse;
	@FXML
	private Button valider;
	@FXML
	private Label label;
	authentificationController hh = new authentificationController();
	// Event Listener on Button[#ajouter].onAction
	@FXML
	public void validerOnAction(ActionEvent event) {
		// TODO Autogenerated
		if (!(nom.getText().isEmpty()) && 
				!(prenom.getText().isEmpty()) &&
				!(mail.getText().isEmpty()) &&
				!(pseudo.getText().isEmpty()) &&
				!(motPasse.getText().isEmpty()) ) {
			//Creation d'un angent
			Agentdescolarite nouvelAgent = new Agentdescolarite();
			nouvelAgent.setMaill(mail.getText());
			nouvelAgent.setMotPasse(motPasse.getText());
			nouvelAgent.setNom(nom.getText());
			nouvelAgent.setPrenom(prenom.getText());
			nouvelAgent.setPseudo(pseudo.getText());
			DirecteurDao dg = new DirecteurDao();
			
			nouvelAgent.setDirecteur(dg.getDirecteurByMatricule(label.getText()));
			//Enregistremment de l'agent dans la bd
			AgentdescolariteDao test = new AgentdescolariteDao();
			test.saveAgent(nouvelAgent);
			nom.setText("");
			prenom.setText("");
			mail.setText("");
			pseudo.setText("");
			motPasse.setText("");
			//ouverture d'une boite de dialogue pour dire que l'enregistrement est fait
			hh.boiteDialogue(AlertType.INFORMATION, "Enregistrement de l'agent en base de dionnées reussi");
		}
		
		else {
			
			hh.boiteDialogue(AlertType.INFORMATION, "Tous les champs doivent être remplis !!!");
		}
		
	}
	
	
	
	public void getBymatricule(String matricul){
		 label.setText(matricul);
		 label.setVisible(false);
	}
}
