package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.control.Button;
import javafx.scene.control.PasswordField;
import javafx.scene.control.TextField;

import java.io.IOException;
import java.util.List;

import com.base.donnees.Agentdescolarite;
import com.base.donnees.Directeur;
import com.base.donnees.Niveau;
import com.gestion.dao.AgentdescolariteDao;
import com.gestion.dao.DirecteurDao;
import com.gestion.dao.NiveauDao;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.layout.BorderPane;
import javafx.stage.Stage;
import javafx.stage.StageStyle;
import javafx.stage.Window;

public class authentificationController {
	@FXML
	private BorderPane border;
	@FXML
	private TextField pseudo;
	@FXML
	private PasswordField passe;
	@FXML
	private Button valider;
	@FXML
	private Button close;
	
	
	
	//Fonction de creation d'une boite de dialogue
	public void boiteDialogue(AlertType s, String contenuMessage) {
		Alert alert = new Alert(s);
		alert.setContentText(contenuMessage);
		alert.show();
	}

	// Event Listener on Button[#valider].onAction
	@FXML
	public void ValiderOnAction(ActionEvent event) {
		// TODO Autogenerated
		 //Recupperation des directeurs
		List < Directeur > directeurs = null;
			DirecteurDao dd = new DirecteurDao();
			directeurs=dd.getAllDirecteur();
			System.out.println("Bonjour");
			System.out.println(directeurs.size());
			 //Recupperation des agents
	   List <Agentdescolarite> agents = null;
	   AgentdescolariteDao agt= new AgentdescolariteDao();
	   agents=agt.getAllAgents();
			if (!(pseudo.getText().isEmpty()) && !(passe.getText().isEmpty())) {
				
				
				for (Directeur directeur : directeurs) {
					if (directeur.getPseudo().equals(pseudo.getText())  && 
						directeur.getMotPasse().equals(passe.getText())  ) {
						
						Stage agentStage = new Stage();
						agentStage.initStyle(StageStyle.UNDECORATED);
						try {
							((Node)event.getSource()).getScene().getWindow().hide();
							FXMLLoader loader = new FXMLLoader(getClass().getResource("Accueil.fxml"));
							Parent root = (Parent) loader.load();
							//passage des données entre fenetre
							
							 AccueilController controller = loader.getController();
							 controller.agentenligne(directeur.getNom(),directeur.getPrenom(),directeur.getMatricule());
								Scene scene = new Scene(root);
								scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
							agentStage.setScene(scene);
								agentStage.show();
								} catch (IOException e) {
								// TODO Auto-generated catch block
								e.printStackTrace();
							}
					}
					
				}
				 
			for (Agentdescolarite agentdescolarite : agents) {
				if (agentdescolarite.getPseudo().equals(pseudo.getText())  && 
						agentdescolarite.getMotPasse().equals(passe.getText()) ) {
					Parent agentSco;
					Stage agentStage = new Stage();
					agentStage.initStyle(StageStyle.UNDECORATED);
					try {
						((Node)event.getSource()).getScene().getWindow().hide();
						FXMLLoader loader = new FXMLLoader(getClass().getResource("Accueil.fxml"));
						Parent root = (Parent) loader.load();
						//passage des données entre fenetre
						
						 AccueilController controller = loader.getController();
						 controller.agentttenligne(agentdescolarite.getNom(),agentdescolarite.getPrenom(),agentdescolarite.getIdAgent().toString());
							Scene scene = new Scene(root);
							scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
						agentStage.setScene(scene);
							agentStage.show();
							} catch (IOException e) {
							// TODO Auto-generated catch block
							e.printStackTrace();
						}
				}
				
				}
			
			 
			 
		}
			
			else {
				boiteDialogue(AlertType.INFORMATION, "Mot de passe ou Pseudo Incorrect OU Tous champs doivent être remplis !!!!");
				pseudo.setText("");
				passe.setText("");
			}

		
		
		
	}
	
	@FXML
	public void closeOnAction(ActionEvent event) {
		((Node)event.getSource()).getScene().getWindow().hide();
	}
}
