package application;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;

import java.net.URL;
import java.util.Date;
import java.util.List;
import java.util.ResourceBundle;

import com.base.donnees.Etudiant;
import com.base.donnees.Filiere;
import com.base.donnees.Niveau;
import com.base.donnees.Versement;
import com.gestion.dao.EtudiantDao;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.layout.AnchorPane;
import javafx.scene.control.Button;
import javafx.scene.control.RadioButton;
import javafx.scene.control.ScrollPane;
import javafx.scene.control.TableView;
import javafx.scene.control.ToggleGroup;
import javafx.scene.control.cell.PropertyValueFactory;
import javafx.scene.control.TableColumn;

public class listeEtudiantController implements Initializable {
	@FXML
	private AnchorPane listeEtudiant;
	@FXML
	private RadioButton Ajour;
	@FXML
	private RadioButton etudiant;
	@FXML
	private RadioButton nonAjour;
	@FXML
	private TableView<Etudiant> tableau;
	@FXML
	private TableColumn<Etudiant, String> matricule;
	@FXML
	private TableColumn<Etudiant, String> nom;
	@FXML
	private TableColumn<Etudiant, String> prenom;
	@FXML
	private TableColumn<Etudiant, String> filiere;
	@FXML
	private TableColumn<Etudiant, String> niveau;
	@FXML
	private TableColumn<Etudiant, Float> paye;
	@FXML
	private TableColumn<Etudiant, Double> restant;
	@FXML
	private ToggleGroup scolarite;
	@FXML
	private Button validerliste;
	@FXML
	private ScrollPane scroller;

	// Event Listener on RadioButton[#Ajour].onAction
	@FXML
	public void AjourOnAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on RadioButton[#etudiant].onAction
	@FXML
	public void etudiantOnAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on RadioButton[#nonAjour].onAction
	@FXML
	public void nonAjourOnAction(ActionEvent event) {
		// TODO Autogenerated
	}
	
	@FXML
	public void validerlisteOnAction(ActionEvent event) {
		// TODO Autogenerated
	}
	@Override
	public void initialize(URL location, ResourceBundle resources) {
		// TODO Auto-generated method stub
		EtudiantDao etd = new EtudiantDao(); 
		List<Etudiant> list = null;
		list=etd.getAllEtudiant();
		ObservableList<Versement> vvv = FXCollections.observableArrayList();
		ObservableList<Etudiant> ettt = FXCollections.observableArrayList();
		for (Etudiant etudiant : list) {
			vvv.addAll(etudiant.getVersements());
		}
		for (Etudiant e : list) {
			ettt.add(new Etudiant(e.getMatricule(), e.getFiliere(), e.getNiveau(), 
					e.getNom(), e.getPrenom(), e.getDateNaissance(), e.getMail(), e.getGenre(), e.getVersements()));
		}
	
		ObservableList<Etudiant> data = FXCollections.observableArrayList();
		data.addAll(ettt);
		matricule.setCellValueFactory(new PropertyValueFactory<Etudiant, String>("matricule"));
		nom.setCellValueFactory(new PropertyValueFactory<Etudiant, String>("nom"));
		prenom.setCellValueFactory(new PropertyValueFactory<Etudiant, String>("prenom"));
		paye.setCellValueFactory(new PropertyValueFactory<Etudiant, Float>("paye"));
		restant.setCellValueFactory(new PropertyValueFactory<Etudiant, Double>("restant"));
		tableau.setItems(data);
	}
}
