package application;

import javafx.fxml.FXML;

import javafx.event.ActionEvent;

import javafx.scene.layout.AnchorPane;
import javafx.scene.control.Button;
import javafx.scene.control.RadioButton;
import javafx.scene.control.ScrollPane;
import javafx.scene.control.TableView;
import javafx.scene.control.ToggleGroup;
import javafx.scene.control.TableColumn;

public class listeEtudiantController {
	@FXML
	private AnchorPane listeEtudiant;
	@FXML
	private RadioButton Ajour;
	@FXML
	private RadioButton etudiant;
	@FXML
	private RadioButton nonAjour;
	@FXML
	private TableView tableau;
	@FXML
	private TableColumn matricule;
	@FXML
	private TableColumn nom;
	@FXML
	private TableColumn prenom;
	@FXML
	private TableColumn paye;
	@FXML
	private TableColumn restant;
	@FXML
	private ToggleGroup scolarite;
	@FXML
	private Button validerliste;
	@FXML
	private ScrollPane scroller;

	// Event Listener on RadioButton[#Ajour].onAction
	@FXML
	public void AjourOnAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on RadioButton[#etudiant].onAction
	@FXML
	public void etudiantOnAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on RadioButton[#nonAjour].onAction
	@FXML
	public void nonAjourOnAction(ActionEvent event) {
		// TODO Autogenerated
	}
	
	@FXML
	public void validerlisteOnAction(ActionEvent event) {
		// TODO Autogenerated
	}
}
