package application;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;

import java.net.URL;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.ResourceBundle;
import java.util.Set;

import com.base.donnees.Etudiant;
import com.base.donnees.Filiere;
import com.base.donnees.Niveau;
import com.base.donnees.Versement;
import com.gestion.dao.EtudiantDao;
import com.gestion.dao.FiliereDao;
import com.gestion.dao.NiveauDao;
import com.gestion.dao.VersementDao;

import javafx.beans.value.ChangeListener;
import javafx.beans.value.ObservableValue;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.layout.AnchorPane;
import javafx.scene.control.Button;
import javafx.scene.control.RadioButton;
import javafx.scene.control.ScrollPane;
import javafx.scene.control.TableView;
import javafx.scene.control.Toggle;
import javafx.scene.control.ToggleGroup;
import javafx.scene.control.cell.PropertyValueFactory;
import javafx.scene.control.TableColumn;

public class listeEtudiantController implements Initializable {
	@FXML
	private AnchorPane listeEtudiant;
	@FXML
	private RadioButton Ajour;
	@FXML
	private RadioButton etudiant;
	@FXML
	private RadioButton nonAjour;
	@FXML
	private TableView<TestEtudiant> tableau;
	@FXML
	private TableColumn<TestEtudiant, String> matricule;
	@FXML
	private TableColumn<TestEtudiant, String> nom;
	@FXML
	private TableColumn<TestEtudiant, String> prenom;
	@FXML
	private TableColumn<TestEtudiant, String> filiere;
	@FXML
	private TableColumn<TestEtudiant, String> niveau;
	@FXML
	private TableColumn<TestEtudiant, Double> paye;
	@FXML
	private TableColumn<TestEtudiant, Double> restant;
	@FXML
	private ToggleGroup scolarite;
	@FXML
	private Button validerliste;
	@FXML
	private ScrollPane scroller;

	// Event Listener on RadioButton[#Ajour].onAction
	@FXML
	public void AjourOnAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on RadioButton[#etudiant].onAction
	@FXML
	public void etudiantOnAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on RadioButton[#nonAjour].onAction
	@FXML
	public void nonAjourOnAction(ActionEvent event) {
		// TODO Autogenerated
	}
	
	@FXML
	public void validerlisteOnAction(ActionEvent event) {
		// TODO Autogenerated
		if (etudiant.isSelected()==true) {
			EtudiantDao etd = new EtudiantDao(); 
			List<Etudiant> list = null;
			list=etd.getAllEtudiant();
			
			
			//ObservableList<Versement> vvv = FXCollections.observableArrayList();
			ObservableList<TestEtudiant> ettt = FXCollections.observableArrayList();
			
			for (Etudiant e : list) {
				 Set<Versement> versEtudiant = new HashSet<Versement>(0);
				 versEtudiant=e.getVersements();
				 double temp = 0 ;
				for (Versement verdd : versEtudiant) {
					temp = temp + verdd.getMontant();
				}
				
				ettt.add(new TestEtudiant(e.getMatricule(), 
											e.getNom(), 
											e.getPrenom(), 
											e.getFiliere().getLibelle(), 
											e.getNiveau().getLibelle(), 
											temp, 
											(e.getNiveau().getMontantScolarite()-temp))
						);
			}
			
			ObservableList<TestEtudiant> data = FXCollections.observableArrayList();
			data.addAll(ettt);
		
			matricule.setCellValueFactory(new PropertyValueFactory<TestEtudiant, String>("Matricule"));
			nom.setCellValueFactory(new PropertyValueFactory<TestEtudiant, String>("Nom"));
			prenom.setCellValueFactory(new PropertyValueFactory<TestEtudiant, String>("Prenom"));
			filiere.setCellValueFactory(new PropertyValueFactory<TestEtudiant, String>("Filiere"));
			niveau.setCellValueFactory(new PropertyValueFactory<TestEtudiant, String>("Niveau"));
			paye.setCellValueFactory(new PropertyValueFactory<TestEtudiant, Double>("Paye"));
			restant.setCellValueFactory(new PropertyValueFactory<TestEtudiant, Double>("Restant"));
			tableau.setItems(data);
		}
		
		if (Ajour.isSelected()==true) {
			EtudiantDao etd = new EtudiantDao(); 
			List<Etudiant> list = null;
			list=etd.getAllEtudiant();
			
			
			//ObservableList<Versement> vvv = FXCollections.observableArrayList();
			ObservableList<TestEtudiant> ettt = FXCollections.observableArrayList();
			
			for (Etudiant e : list) {
				 Set<Versement> versEtudiant = new HashSet<Versement>(0);
				 versEtudiant=e.getVersements();
				 double temp = 0 ;
				for (Versement verdd : versEtudiant) {
					temp = temp + verdd.getMontant();
				}
				
			
				
				if (temp == e.getNiveau().getMontantScolarite()) {
					ettt.add(new TestEtudiant(e.getMatricule(), 
							e.getNom(), 
							e.getPrenom(), 
							e.getFiliere().getLibelle(), 
							e.getNiveau().getLibelle(), 
							temp, 
							(e.getNiveau().getMontantScolarite()-temp)));
				}
				
			}
			
			ObservableList<TestEtudiant> data = FXCollections.observableArrayList();
			data.addAll(ettt);
		
			matricule.setCellValueFactory(new PropertyValueFactory<TestEtudiant, String>("Matricule"));
			nom.setCellValueFactory(new PropertyValueFactory<TestEtudiant, String>("Nom"));
			prenom.setCellValueFactory(new PropertyValueFactory<TestEtudiant, String>("Prenom"));
			filiere.setCellValueFactory(new PropertyValueFactory<TestEtudiant, String>("Filiere"));
			niveau.setCellValueFactory(new PropertyValueFactory<TestEtudiant, String>("Niveau"));
			paye.setCellValueFactory(new PropertyValueFactory<TestEtudiant, Double>("Paye"));
			restant.setCellValueFactory(new PropertyValueFactory<TestEtudiant, Double>("Restant"));
			tableau.setItems(data);
		}
		
		if (nonAjour.isSelected() == true ) {
			EtudiantDao etd = new EtudiantDao(); 
			List<Etudiant> list = null;
			list=etd.getAllEtudiant();
			
			
			//ObservableList<Versement> vvv = FXCollections.observableArrayList();
			ObservableList<TestEtudiant> ettt = FXCollections.observableArrayList();
			
			for (Etudiant e : list) {
				 Set<Versement> versEtudiant = new HashSet<Versement>(0);
				 versEtudiant=e.getVersements();
				 double temp = 0 ;
				for (Versement verdd : versEtudiant) {
					temp = temp + verdd.getMontant();
				}
				
				
				
				if (temp < e.getNiveau().getMontantScolarite()) {
					ettt.add(new TestEtudiant(e.getMatricule(), 
							e.getNom(), 
							e.getPrenom(), 
							e.getFiliere().getLibelle(), 
							e.getNiveau().getLibelle(), 
							temp, 
							(e.getNiveau().getMontantScolarite()-temp)));
				}
				
			}
			
			ObservableList<TestEtudiant> data = FXCollections.observableArrayList();
			data.addAll(ettt);
		
			matricule.setCellValueFactory(new PropertyValueFactory<TestEtudiant, String>("Matricule"));
			nom.setCellValueFactory(new PropertyValueFactory<TestEtudiant, String>("Nom"));
			prenom.setCellValueFactory(new PropertyValueFactory<TestEtudiant, String>("Prenom"));
			filiere.setCellValueFactory(new PropertyValueFactory<TestEtudiant, String>("Filiere"));
			niveau.setCellValueFactory(new PropertyValueFactory<TestEtudiant, String>("Niveau"));
			paye.setCellValueFactory(new PropertyValueFactory<TestEtudiant, Double>("Paye"));
			restant.setCellValueFactory(new PropertyValueFactory<TestEtudiant, Double>("Restant"));
			tableau.setItems(data);
		}
		}
		
	
	@Override
	public void initialize(URL location, ResourceBundle resources) {
		// TODO Auto-generated method stub
		EtudiantDao etd = new EtudiantDao(); 
		List<Etudiant> list = null;
		list=etd.getAllEtudiant();
		
		
	
		ObservableList<TestEtudiant> ettt = FXCollections.observableArrayList();
		
		for (Etudiant e : list) {
			System.out.println(e.getMatricule());
			//System.out.println(e.getNiveau().getLibelle());
			 Set<Versement> versEtudiant = new HashSet<Versement>(0);
			 versEtudiant=e.getVersements();
			 double temp = 0 ;
			for (Versement verdd : versEtudiant) {
				temp = temp + verdd.getMontant();
			}
			
		
			
			ettt.add(new TestEtudiant(e.getMatricule(), 
										e.getNom(), 
										e.getPrenom(), 
										e.getFiliere().getLibelle(), 
										e.getNiveau().getLibelle(), 
										temp, 
										(e.getNiveau().getMontantScolarite()-temp)));
		}
		
		ObservableList<TestEtudiant> data = FXCollections.observableArrayList();
		data.addAll(ettt);
	
		matricule.setCellValueFactory(new PropertyValueFactory<TestEtudiant, String>("Matricule"));
		nom.setCellValueFactory(new PropertyValueFactory<TestEtudiant, String>("Nom"));
		prenom.setCellValueFactory(new PropertyValueFactory<TestEtudiant, String>("Prenom"));
		filiere.setCellValueFactory(new PropertyValueFactory<TestEtudiant, String>("Filiere"));
		niveau.setCellValueFactory(new PropertyValueFactory<TestEtudiant, String>("Niveau"));
		paye.setCellValueFactory(new PropertyValueFactory<TestEtudiant, Double>("Paye"));
		restant.setCellValueFactory(new PropertyValueFactory<TestEtudiant, Double>("Restant"));
		tableau.setItems(data);
}
	}
