package application;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.scene.control.ToggleGroup;
import javafx.scene.control.Alert.AlertType;

import java.net.URL;
import java.sql.Date;
import java.time.LocalDate;
import java.util.List;
import java.util.ResourceBundle;

import com.base.donnees.Etudiant;
import com.base.donnees.Filiere;
import com.base.donnees.Niveau;
import com.gestion.dao.EtudiantDao;
import com.gestion.dao.FiliereDao;
import com.gestion.dao.NiveauDao;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.control.ComboBox;

import javafx.scene.layout.AnchorPane;

import javafx.scene.control.RadioButton;

import javafx.scene.control.DatePicker;
import javafx.scene.control.Label;

public class ModifierEtudiantController implements Initializable {
	@FXML
	private AnchorPane contenu;
	@FXML
	private TextField matricule;
	@FXML
	private TextField nom;
	@FXML
	private TextField prenom;
	@FXML
	private DatePicker date;
	@FXML
	private TextField mail;
	@FXML
	private RadioButton masculin;
	@FXML
	private ToggleGroup genre;
	@FXML
	private RadioButton feminin;
	@FXML
	private ComboBox filiere;
	@FXML
	private ComboBox niveau;
	@FXML
	private ComboBox EtudiantModif;
	@FXML
	private Button modifier;
	@FXML 
	private Label etudiantamodifier;

	// Event Listener on ComboBox[#filiere].onAction
	@FXML
	public void filiereOnAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ComboBox[#niveau].onAction
	@FXML
	public void niveauOnAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#modifier].onAction
	@FXML
	public void modifierOnAction(ActionEvent event) {
		// TODO Autogenerated
		String EtaS= EtudiantModif.getSelectionModel().getSelectedItem().toString();
		EtudiantDao etd = new EtudiantDao();
		Etudiant etudiant = new Etudiant();
		etudiant=etd.getEtudiantByMatricule(EtaS);
		
		System.out.println(etudiant.getMail()+" "+etudiant.getNom());
		String matricule_Etudiant = matricule.getText();
		String nom_Etudiant = nom.getText();
		String prenom_Etudiant = prenom.getText();
		LocalDate dat = date.getValue();
		Date date= Date.valueOf(dat);
		//System.out.println(filiere.getSelectionModel().getSelectedItem().toString());
		
		etudiant.setMatricule(matricule_Etudiant);
		etudiant.setNom(nom_Etudiant);
		etudiant.setPrenom(prenom_Etudiant);
		etudiant.setDateNaissance(date);
		
		if (masculin.isSelected()==true) {
			etudiant.setGenre("Masculin");
		}
		if (feminin.isSelected()==true) {
			etudiant.setGenre("Feminin");
		} 
		//recupperation de la filiere
		List<Filiere> filieres = null;
		FiliereDao kk = new FiliereDao();
		filieres=kk.getAllFiliere();

		String filiereChoisie = filiere.getSelectionModel().getSelectedItem().toString();
			for (Filiere filiere : filieres) {
				if (filiere.getLibelle().equals(filiereChoisie)) {
					etudiant.setFiliere(filiere);
					
				}
					}
	
		//recupperation du niveau
			 List < Niveau > niveaux = null;
				NiveauDao dd = new NiveauDao();
				niveaux=dd.getAllNiveau();
				
				String niveauChoisie = niveau.getSelectionModel().getSelectedItem().toString();
				for (Niveau niveau : niveaux) {
				
					if (niveau.getLibelle().equals(niveauChoisie)) {
						etudiant.setNiveau(niveau);
						
					}
					
				}
				
		etudiant.setMail(mail.getText());
		etd.updateEtudiant(etudiant);
		authentificationController auth = new authentificationController();
		auth.boiteDialogue(AlertType.INFORMATION, "Etudiant Modifier avec succès!!!");
		
		//on remet le contenu de tous les champs à vide
		mail.setText("");
		nom.setText("");
		prenom.setText("");
		masculin.setSelected(false);
		feminin.setSelected(false);
		this.date.setValue(null);
		this.date.getEditor().clear();
		filiere.setValue(null);
		niveau.setValue(null);
		matricule.setText(null);
		
		AccueilController acc = new AccueilController();
		acc.chargementFonction("listeEtudiant.fxml");
	}
	@Override
	public void initialize(URL location, ResourceBundle resources) {
		// TODO Auto-generated method stub
		//ObservableList< String> liste = FXCollections.observableArrayList("java","php","C","python");
		//filiere.setItems(liste);
		
		//Remplissage du comboBox avec les elemenst de la classe Niveau
		 List < Niveau > niveaux = null;
			NiveauDao dd = new NiveauDao();
			niveaux=dd.getAllNiveau();
			ObservableList<String> listeNiveau = FXCollections.observableArrayList();
			
			for (Niveau niveau : niveaux) {
				
				listeNiveau.add(niveau.getLibelle());	
			}
			
			niveau.setItems(listeNiveau);
		
		//Remplissage du comboBox avec leselemenst de la classe Filiere
			List<Filiere> filieres = null;
			FiliereDao kk = new FiliereDao();
			filieres=kk.getAllFiliere();
			ObservableList<String> listeFiliere = FXCollections.observableArrayList();
				for (Filiere filiere : filieres) {
								
								listeFiliere.add(filiere.getLibelle())	;
							}
				filiere.setItems(listeFiliere);
				
		//remplissage du combobox avec les elements de la classe etudiant
				 List < Etudiant > etudiants = null;
				 EtudiantDao etd = new EtudiantDao();
				 etudiants=etd.getAllEtudiant();
					ObservableList<Object> listeEtudiant = FXCollections.observableArrayList();
					
					for (Etudiant etudiant : etudiants) {
						listeEtudiant.add(etudiant.getMatricule()/* +"- "+etudiant.getNom()+" "+etudiant.getPrenom() */);
						
					}
					
					EtudiantModif.setItems(listeEtudiant);
		
	}
	
	
}
