package application;

import java.net.URL;
import java.util.List;
import java.util.ResourceBundle;

import com.base.donnees.Agentdescolarite;
import com.gestion.dao.AgentdescolariteDao;
import com.gestion.dao.EtudiantDao;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;
import javafx.scene.control.ComboBox;
import javafx.scene.control.Alert.AlertType;



public class supprimerAgentController implements Initializable {
	@FXML
	private ComboBox id_agent;
	@FXML
	private Button supprimer;

	// Event Listener on Button[#supprimer].onAction
	@FXML
	public void supprimerOnAction(ActionEvent event) {
		// TODO Autogenerated
		int id;
		String str= new String();
		str=id_agent.getSelectionModel().getSelectedItem().toString();
		str = str.replaceAll("[^\\d]", "");
		id=Integer.parseInt(str);
		AgentdescolariteDao agt = new AgentdescolariteDao();
		agt.SupprimerAgent(id);
		authentificationController auth = new authentificationController();
		auth.boiteDialogue(AlertType.INFORMATION, "Agent de scolarité suppprimé avec succès!!!");
	}

	@Override
	public void initialize(URL location, ResourceBundle resources) {
		// TODO Auto-generated method stub
		//Remplissage du comboBox avec les elemenst de la classe agent
		 List < Agentdescolarite > agents = null;
		 AgentdescolariteDao agt= new AgentdescolariteDao();
			agents=agt.getAllAgents();
		
			ObservableList<Object> listeAgent = FXCollections.observableArrayList();
			
			for (Agentdescolarite agent : agents) {
				Integer idAgent;
				idAgent=agent.getIdAgent();
				String gg = new String();
				gg=String.valueOf(idAgent);
				String nom = agent.getNom();
				String prenom = agent.getPrenom();
				listeAgent.add(gg+"- "+nom+" "+prenom);
				
			}
			
			id_agent.setItems(listeAgent);
		
	}
	
}
