package application;

import java.net.URL;
import java.util.List;
import java.util.ResourceBundle;

import com.base.donnees.Agentdescolarite;
import com.gestion.dao.AgentdescolariteDao;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;
import javafx.scene.control.ComboBox;



public class supprimerAgentController implements Initializable {
	@FXML
	private ComboBox id_agent;
	@FXML
	private Button supprimer;

	// Event Listener on Button[#supprimer].onAction
	@FXML
	public void supprimerOnAction(ActionEvent event) {
		// TODO Autogenerated
	}

	@Override
	public void initialize(URL location, ResourceBundle resources) {
		// TODO Auto-generated method stub
		//Remplissage du comboBox avec les elemenst de la classe agent
		 List < Agentdescolarite > agents = null;
		 AgentdescolariteDao agt= new AgentdescolariteDao();
			agents=agt.getAllAgents();
		
			ObservableList<Object> listeAgent = FXCollections.observableArrayList();
			
			for (Agentdescolarite agent : agents) {
				listeAgent.add("N°"+agent.getIdAgent()+"- "+agent.getNom()+" "+agent.getPrenom());
				
			}
			
			id_agent.setItems(listeAgent);
		
	}
	
}
