package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.layout.AnchorPane;

public class SupprimerEtudiantController {
	@FXML
	private AnchorPane border;
	@FXML
	private TextField matricule;
	@FXML
	private Button supprimer;

	// Event Listener on Button[#supprmer].onAction
	@FXML
	public void SupprimerOnAction(ActionEvent event) {
		// TODO Autogenerated
	}
}
