package application;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;


public class supprimerAgentController {
	@FXML
	private TextField id_agent;
	@FXML
	private Button supprimer;

	// Event Listener on Button[#supprimer].onAction
	@FXML
	public void supprimerOnAction(ActionEvent event) {
		// TODO Autogenerated
	}
}
