package application;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import java.net.URL;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;

import javafx.scene.layout.AnchorPane;

import javafx.scene.control.DatePicker;

public class VersementController implements Initializable {
	@FXML
	private AnchorPane versement;
	@FXML
	private TextField matricule;
	@FXML
	private TextField id_agent;
	@FXML
	private TextField montant;
	@FXML
	private Button valider;
	@FXML
	private DatePicker date_versement;

	// Event Listener on Button[#valider].onAction
	@FXML
	public void ValiderOnAction(ActionEvent event) {
		// TODO Autogenerated
	}

	@Override
	public void initialize(URL location, ResourceBundle resources) {
		// TODO Auto-generated method stub
		
	}
	
	public void matriculeDefaut(String s) {
		
		matricule.setText(s);
		matricule.setEditable(false);
	}
	public void Id_agentdefaut(String s) {
		id_agent.setText(s);
		id_agent.setEditable(false);
	}
	public void id_agent(String s) {
		id_agent = new TextField();
		id_agent.setText(s);
		id_agent.setEditable(false);
	}
}
