package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.layout.AnchorPane;

import javafx.scene.control.DatePicker;

public class VersementController {
	@FXML
	private AnchorPane versement;
	@FXML
	private TextField matricule;
	@FXML
	private TextField id_agent;
	@FXML
	private TextField montant;
	@FXML
	private Button valider;
	@FXML
	private DatePicker date_versement;

	// Event Listener on Button[#valider].onAction
	@FXML
	public void ValiderOnAction(ActionEvent event) {
		// TODO Autogenerated
	}
}
